// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMEj5D9ummCqRpB-1lXpbrU7saco_m3iM',
    appId: '1:384892533366:web:2269b04b76773f7dc3bd57',
    messagingSenderId: '384892533366',
    projectId: 'emart-63887',
    authDomain: 'emart-63887.firebaseapp.com',
    storageBucket: 'emart-63887.appspot.com',
    measurementId: 'G-0R5EZHV4JP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1TPOw2tjiiYN-VaBVxRjMxxWThnbByME',
    appId: '1:384892533366:android:5c74d224fe3ff6a9c3bd57',
    messagingSenderId: '384892533366',
    projectId: 'emart-63887',
    storageBucket: 'emart-63887.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMFjLx4liTrvg7a3BjCHYxkyo4Qpbyr_4',
    appId: '1:384892533366:ios:6944edfb5414dd62c3bd57',
    messagingSenderId: '384892533366',
    projectId: 'emart-63887',
    storageBucket: 'emart-63887.appspot.com',
    iosBundleId: 'com.example.emartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMFjLx4liTrvg7a3BjCHYxkyo4Qpbyr_4',
    appId: '1:384892533366:ios:6944edfb5414dd62c3bd57',
    messagingSenderId: '384892533366',
    projectId: 'emart-63887',
    storageBucket: 'emart-63887.appspot.com',
    iosBundleId: 'com.example.emartApp',
  );
}
